part of 'theme.dart';

// Icons
final kIcAddPhoto = Image.asset('assets/icons/ic_add_photo.png');
final kIcApp = Image.asset('assets/icons/ic_app.png');
final kIcApple = Image.asset('assets/icons/ic_apple.png');
final kIcCamera = Image.asset('assets/icons/ic_camera.png');
final kIcCar = Image.asset('assets/icons/ic_car.png');
final kIcDelete = Image.asset('assets/icons/ic_delete.png');
final kIcDistance = Image.asset('assets/icons/ic_distance.png');
final kIcDone = Image.asset('assets/icons/ic_done.png');
final kIcFB = Image.asset('assets/icons/ic_fb.png');
final kIcGoogle = Image.asset('assets/icons/ic_google.png');
final kIcHome2 = Image.asset('assets/icons/ic_home_2.png');
final kIcHome = Image.asset('assets/icons/ic_home.png');
final kIcIdea = Image.asset('assets/icons/ic_idea.png');
final kIcListOutline = Image.asset('assets/icons/ic_list_outline.png');
final kIcList = Image.asset('assets/icons/ic_list.png');
final kIcMastercard = Image.asset('assets/icons/ic_mastercard.png');
final kIcNewsOutline = Image.asset('assets/icons/ic_news_outline.png');
final kIcNewsSolid = Image.asset('assets/icons/ic_news_solid.png');
final kIcOutline = Image.asset('assets/icons/ic_outline.png');
final kIcPaypal = Image.asset('assets/icons/ic_paypal.png');
final kIcQR = Image.asset('assets/icons/ic_qr.png');
final kIcSetting = Image.asset('assets/icons/ic_setting.png');
final kIcSettings = Image.asset('assets/icons/ic_settings.png');
final kIcSolid = Image.asset('assets/icons/ic_solid.png');
final kIcTokenMoney = Image.asset('assets/icons/ic_token_money.png');
final kIcVisa = Image.asset('assets/icons/ic_visa.png');
final kIcHumanRun = Image.asset('assets/icons/ic56_human_run.png');
final kIcHumanWalk = Image.asset('assets/icons/ic56_human_walk.png');
final kIcHuman = Image.asset('assets/icons/ic56_human.png');
final kIcCarSimple = Image.asset('assets/icons/ic64_car_simple.png');
final kIcCycling = Image.asset('assets/icons/ic64_cycling.png');
final kIcRunShoes = Image.asset('assets/icons/ic64_run_shoes.png');
